Dev/members
GDSC-CAU/GDSC-SPACE pull request #22
Opened 2023-08-14 08:13 UTC by pjw-redt

## Summary
MemberCard 단일 객체 1차 구현 완료

## Description
MemberCard 단일 객체 1차 구현 완료했습니다!
MemberCard List와 core표시, 기수 구분은 내일까지 완료할 예정입니다.

2023-08-14 11:19 UTC, danpacho requested changes
피드백 확인 부탁드립니다!

2023-08-14 11:55 UTC, pjw-redt commented on public/yymin1022.png
넵 사진은 앞으로 삭제하고 push 하겠습니다!

2023-08-14 18:20 UTC, yymin1022 reviewed
이전에 준성님 리뷰에서 요청사항 몇가지가 반영되지 않은 것 같네요.
이외의 구현은 LGTM입니다!

@danpacho @pjw-redt 코멘트 달린 것 중에, Resolved로 뜨는 것이 있는데, 이렇게되면 접혀서 안보이게 되니까 되도록이면 Resolve하지 않고 두는 것으로 하면 어떨까요? 확인이 번거로운 것 같아서요

2023-08-14 18:20 UTC, yymin1022 commented on src/app/members/page.tsx
> +export type MemberData = {
요거 type 이름이 `MemberData`라고 되어있는데, `Data`는 불필요한 `Suffix`라고 준성님이 이전 Review에서 언급하셨던 것 같아요! 간단한거니까 수정하면 어떨까 싶네요

2023-08-15 00:49 UTC, danpacho commented
넵 좋습니다!

2023-08-15 01:13 UTC, danpacho commented on src/app/members/page.tsx
> +export type MemberData = {
suffix 단어 배우고 갑니다!

2023-08-15 04:13 UTC, yymin1022 approved these changes

2023-08-15 04:14 UTC, merged